### PR TITLE
handle nodes being down better

### LINKED ISSUE #1512: Hunts - handle nodes being down better
Currently if during a hunt a node is down or having an issue the hunt errors out and pauses. Instead we should save the session ids that failed with the hunt and then try them again at the end. My general thought is
* Do the hunt as normal, any sessionId that fails because of the remote node being down, save the session id in something like hunts.failedSessionIds array in write back to ES occasionally
* After the normal hunt has failed then go back thru all the failedSessionIds, deleting the ones that no longer fail
* Repeat until either no more failedSessionIds (success!) or a complete run thru the error with no changes (pause for error)
* May want to have a max failedSessionIds length (I think ES has a 32k array limit) in which case we should pause for error 
* If someone reruns it should delete the failedSessionIds

Bonus, the bar chart thingy should either 
a) not count the failed sessions as being done
b) should display 3 sections (failed, done, not done)

The details display should probably show how many are waiting to retry

### PR DESCRIPTION
**Pull request by 31453**
if remote node is down, skip the session and go back through skipped sessions later
consolidate redundant ui components for status and hunt details
don't display skipped hunts in progress bar
indicate number of skipped hunts in hunt details
if failed sessions exceed 10k, pause with an error

fixes #1512

### CODE REVIEW

File: viewer/viewer.js [hunk 1]
```diff
@@ -7686,35 +7701,112 @@ function buildHuntOptions (huntId, hunt) {
...
     let hits = result.hits.hits;
-
     if (searchedSessions === undefined) {
       searchedSessions = hunt.searchedSessions || 0;
       // if the session query results length is not equal to the total sessions that the hunt
       // job is searching, update the hunt total sessions so that the percent works correctly
-      if (hunt.totalSessions !== (result.hits.total + searchedSessions)) {
-        hunt.totalSessions = result.hits.total + searchedSessions;
-      }
+      // TODO ECR - this borks rerunning through the failed sessions - the totalSessions gets incremented
```
Comment (31453) [inline viewer/viewer.js:7796]: @awick What was the original purpose of this? Why was the percent not working correctly? Because of the scroll stuff?

If I keep this in when there are failed sessions, it just keeps incrementing the searched sessions.

Comment (awick) [reply viewer/viewer.js:7796]: If I remember right, sessions could be added during the scroll so previous totalSessions would be wrong.

Comment (31453) [reply viewer/viewer.js:7802]: 👍 I left it in to see how it works with real data, since the test data never hits the scroll

File: viewer/viewer.js [hunk 2]
```diff
@@ -7702,14 +7701,15 @@ function continueHuntSkipSession (hunt, huntId, session, sessionId, searchedSess
   updateHuntStats(hunt, huntId, session, searchedSessions, cb);
 }
 
+let searchingFailedSessions = false; // TODO ECR - a better place to put this? internals?
```
Comment (31453) [inline viewer/viewer.js:7704]: @awick thoughts on the best place to put this?

Comment (awick) [reply viewer/viewer.js:7704]: Ya shouldn't be a global incase somehow multiple hunts are running or some other badness. I would look at having buildHuntOptions put it inside of options if that would work.

Comment (31453) [reply viewer/viewer.js]: 👍 I put it on the hunt options object

File: viewer/viewer.js [hunk 3]
```diff
@@ -7686,24 +7686,124 @@ function buildHuntOptions (huntId, hunt) {
   return options;
 }
 
+// if we couldn't retrieve the seession, skip it but add it to failedSessionIds
+// so that we can go back and search for it at the end of the hunt
+function continueHuntSkipSession (hunt, huntId, session, sessionId, searchedSessions, cb) {
+  if (!hunt.failedSessionIds) {
+    hunt.failedSessionIds = [ sessionId ];
+  } else {
+    if (hunt.failedSessionIds.length > 10000) { // TODO ECR - is this a good limit? ES doesn't specifically have an array size limit, but it does get costly to update a document if there is a large field
```
Comment (31453) [inline viewer/viewer.js:7695]: @awick what do you think the limit should be?

Comment (awick) [reply viewer/viewer.js:7695]: 10k seems a fine place to start

Comment (31453) [reply viewer/viewer.js:7695]: 👍

File: viewer/viewer.js [hunk 4]
```diff
@@ -7686,24 +7686,126 @@ function buildHuntOptions (huntId, hunt) {
...
+  return updateHuntStats(hunt, huntId, session, searchedSessions, cb);
+}
+
+// if there are failed sessions, go through them one by one and do a packet search
+// if there are no failed sessions left at the end then the hunt is done
+// if there are still failed sessions, but some sessions were searched during the last pass, try again
+// if there are still failed sessions, but no new sessions coudl be searched, pause the job with an error
+function huntFailedSessions (hunt, huntId, options, searchedSessions, user) {
+  let changesSearchingFailedSessions = false;
+  if (hunt.failedSessionIds && hunt.failedSessionIds.length) {
```
Comment (awick) [inline viewer/viewer.js:7717]: style thing, would prefer a ! with a return here, so the rest of the function isn't indented.

File: viewer/viewer.js [hunk 5]
```diff
@@ -7686,24 +7686,126 @@ function buildHuntOptions (huntId, hunt) {
...
+    options.searchingFailedSessions = true;
+    // copy the failed session ids so we can remove them from the hunt
+    // but still loop through them iteratively
+    let failedSessions = JSON.parse(JSON.stringify(hunt.failedSessionIds));
+    // we don't need to search the db for session, we just need to search each session in failedSessionIds
+    async.forEachLimit(failedSessions, 3, function (sessionId, cb) {
+      Db.get(Db.sid2Index(sessionId), 'session', Db.sid2Id(sessionId))
```
Comment (awick) [inline viewer/viewer.js:7724]: this should use Db.getSession if possible

**Review by awick — COMMENTED** [review]
minor stuff, feel free to ignore

File: viewer/viewer.js (hunk 4 above)
Comment (31453) [reply viewer/viewer.js:7717]: 👍

File: viewer/viewer.js (hunk 5 above)
Comment (31453) [reply viewer/viewer.js:7724]: Does Db.getSession get the session even if it's on a remote node? So I won't have to do the make request part too?

Comment (31453) [reply viewer/viewer.js:7724]: or do something like this:

  ```
Db.getSession(sessionId, {}, (err, session) => {
      if (err) {
        return continueHuntSkipSession(hunt, huntId, session, sessionId, searchedSessions, cb); 
      }
      
      makeRequest(session.node, `${session.node}/hunt/${huntId}/remote/${sessionId}`, user, (err, response) => {
        if (err) {
          return continueHuntSkipSession(hunt, huntId, session, sessionId, searchedSessions, cb);
        }

        let json = JSON.parse(response);

        if (json.error) {
          console.log(`Error hunting on remote viewer: ${json.error} - ${path}`);
          return continueHuntSkipSession(hunt, huntId, session, sessionId, searchedSessions, cb);
        }

        // remove from failedSessionIds if it was found
        hunt.failedSessionIds.splice(hunt.failedSessionIds.indexOf(sessionId), 1);
        // there were changes to this hunt; we're making progress
        changesSearchingFailedSessions = true;

        if (json.matched) { hunt.matchedSessions++; }
        return updateHuntStats(hunt, huntId, session, searchedSessions, cb);
      });
    });
```

Comment (31453) [reply viewer/viewer.js:7724]: And I don't need to pass it options because I don't need any fields. I just need the packets. Right?

Comment (awick) [reply viewer/viewer.js:7724]: Oh i just realized it doesn't have a promise version :( And yes you can just do {} for options, although I think you just need the ['lastPacket', 'node', 'huntId', 'huntName', 'fileId'] fields.

Comment (31453) [reply viewer/viewer.js]: 👍 works perfectly. I forgot that function existed!
